<a href="https://colab.research.google.com/github/ChunJaeSeung/test_project/blob/main/lesson_01_contents_orientation_%26_numpy_1_array%2C_zero%2C_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 목차
    - numpy
    - pandas
    - matplotlib & seaborn
    - scikit-learn

### Numpy
    - 행렬 연산을 가능하게 해주는 패키지
    - python으로 작성되나 연산은 C, C++, 포트란으로 진행
        - 선형대수 연산을 빠르게 할 수 있음

In [1]:
import numpy as np   # 넘파이 라이브러리 불러오기, 및 np로 작성시 넘파이 사용약속
# 배열객체 = #생성자 함수  #파이썬 리스트
ary = np.array([1, 2, 3], dtype = 'int32')
type(ary), ary

(numpy.ndarray, array([1, 2, 3], dtype=int32))

    - ndarray : 한가지 데이터 타입만으로 사용이 가능

In [2]:
ary2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(ary2)       # 행렬 확인
print(ary2.ndim)   # 행렬의 차원
print(ary2.shape)  # 행렬의 형태
print(ary2.size)   # 행렬 내 원소개수
print(ary2.dtype) # 행렬의 자료형

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [ ]:
help(np.random.randint)

In [4]:
a = np.random.randint(2, 10, size=(5,))
b = np.random.randint(2, 10, size=(2, 4))
c = np.random.randint(2, 10, size=(2, 3, 4))
print(a)
print(b)
print(c)

[8 2 4 6 2]
[[3 4 5 5]
 [7 4 8 6]]
[[[4 4 6 7]
  [5 9 5 5]
  [7 5 6 8]]

 [[5 5 4 5]
  [7 3 5 7]
  [5 5 2 2]]]


In [5]:
ary2.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
ary2[1]

array([4, 5, 6])

In [7]:
ary2[1, 1]

5

#### 데이터 수정

In [8]:
ls = [1, 2, 3]
ls[1] = 5
ls

[1, 5, 3]

In [9]:
ary3 = np.array([[1, 2, 3],
                 [0, 1, 0]])
ary3[1][1] = 0
ary3

array([[1, 2, 3],
       [0, 0, 0]])

##### array 브로드캐스팅

In [ ]:
ary3[0] = 0
ary3

array([[0, 0, 0],
       [0, 0, 0]])

##### array 조건 선택

In [10]:
ary3[0] = 5
ary3[1] = [5, 6, 7]
ary3

array([[5, 5, 5],
       [5, 6, 7]])

In [11]:
idx = ary3 > 5
idx

array([[False, False, False],
       [False,  True,  True]])

In [12]:
ary3[idx]

array([6, 7])

In [13]:
ary3[ary3 > 5] #위에 코드와 같음

array([6, 7])

##### 조건에 맞는 값만 변경

In [15]:
ary3[idx] = 100
ary3

array([[  5,   5,   5],
       [  5, 100, 100]])

In [14]:
ary3[ary3 > 5] = 100
print(ary3)

[[  5   5   5]
 [  5 100 100]]


#### zero array

In [18]:
zero_ary = np.zeros(shape = (2, 3))
zero_ary

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
type(zero_ary)

numpy.ndarray

In [19]:
zero_ary.dtype # 실수형 값만 바꿔 넣을 수 있음

dtype('float64')

##### array안의 데이터 형태 변경

In [21]:
z2 = zero_ary.astype('int64') # 타입 바꿀 때 뒤에 숫자는 안바꾸는게 좋다. 바꾸면 데이터가 날라갈수도 있음.
z2.dtype

dtype('int64')

#### one array

In [22]:
one_ary = np.ones((2, 3)) # shape을 적어도 되고 빼도 자동으로 shape 된다.
one_ary.dtype, one_ary

(dtype('float64'), array([[1., 1., 1.],
        [1., 1., 1.]]))

In [23]:
one_ary2 = np.ones((2, 3, 2)).astype('int')
one_ary2.dtype, one_ary2

(dtype('int64'), array([[[1, 1],
         [1, 1],
         [1, 1]],
 
        [[1, 1],
         [1, 1],
         [1, 1]]]))

In [24]:
id = np.identity(n = 5, dtype = np.int8) # 단위 행렬
id # n의 숫자를 바꾸면 크기가 바뀐다

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

#### 범위값 array 생성

In [25]:
ary4 = np.arange(1, 11) # 끝 숫자는 항상 빼기 1 해야한다.
ary4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])